name: Secret in action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/map-input
        with:
          stuff:
            thing: hello from inside!
