# This is a basic workflow to help you get started with Actions

name: Git tests

# Controls when the workflow will run
on:
  push:

jobs:
  build-matrix-data:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - shell: bash
        id: set-input
        run: |
          echo "json=[{\"name\":\"testA\",\"java-version\":\"17\",\"maven-module\":\"testA\"},{\"name\":\"testB\",\"java-version\":\"17\",\"maven-module\":\"testB\"}]" >> $GITHUB_OUTPUT
      - shell: bash
        id: set-matrix
        run: |
          echo 'matrix=${{ steps.set-input.outputs.json }}' >> $GITHUB_OUTPUT
          
        
  matrix-job:
    runs-on: ubuntu-latest
    needs: build-matrix-data
    strategy:
      matrix:
        include: ${{ fromJson(needs.build-matrix-data.outputs.matrix) }}
    steps:
      - shell: bash
        run: |
          echo "${{ matrix.name }}"
          

