# This is a basic workflow to help you get started with Actions

name: Git tests

# Controls when the workflow will run
on:
  push:

jobs:
  build-matrix-data:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - shell: bash
        id: set-matrix
        run: |
          echo ::set-output name=matrix::'[{"java-version":"17",},"name":"spoon-feeder","maven-module":"spoon-feeder"}]'
        
  matrix-job:
    runs-on: ubuntu-latest
    needs: set-matrix-input
    strategy:
      matrix:
        include: ${{ fromJson(needs.build-matrix-data.outputs.matrix) }}
    steps:
      - shell: bash
        run: |
          echo "${{ matrix.name }}"
          

