name: 'output testing'


on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  json_validation:
    name: 'Input validation'
    runs-on: ubuntu-latest
    steps:

    - name: Json format check
      id: json_format_check
      run: for file in $(find . -type f -name *.json); do $(cat $file | jq empty) || echo "$file is not a valid json file"; done
      continue-on-error: true

    - name: Control character check
      id: ctrl_char_check
      run: grep "{" -r . | sed "s/:.*//g" | uniq
      continue-on-error: true

    - name: Display outputs
      run: echo "json outcome is ${{ steps.json_format_check.outcome }}" && echo "json output is ${{ steps.json_format_check.outputs.stdout }}" && echo "char check output is ${{ steps.ctrl_char_check.outputs.stdout }}" && echo "char check length is ${{ steps.json_format_check.outputs.stdout.length }}"
      
    #- name: Test script
    #  uses: actions/github-script@v6
    #  if: github.event_name == 'pull_request'
    #  with:
    #    github-token: ${{ secrets.TOKEN }}
    #    script: |
    #      const output = `${{ steps.json_format_check.outputs.stdout }}`
  
