name: PR Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Eclion"
          git config --global pull.rebase true

          git switch -c tests/pr
          git pull origin tests/pr

          echo "$(date +%Y%M%d%H%m%s)" > my-new-file.txt
          git add .
          
          git diff --staged

          git commit -m "auto: $(date +%Y%M%d%H%m)"
          git push origin tests/pr

          PR_TITLE="PR test"
          if ! $(gh pr list | grep -q "$PR_TITLE"); then
            gh pr create \
              --base master \
              --body "" \
              --title "$PR_TITLE"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
       
